name: Picassco Deployment (API)
on:
    push:
        branches:
            - stable
            - "releases/**"
    pull_request:
        branches:
            - stable
            - "releases/**"
env:
    FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
    deploy:
        name: Deploy app
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: wei/curl@master
              with:
                args: -o prod.env ${{ secrets.URL_ENV }}
            - uses: superfly/flyctl-actions@1.1
              with:
                  args: "deploy"
